// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countUsersStmt, err = db.PrepareContext(ctx, countUsers); err != nil {
		return nil, fmt.Errorf("error preparing query CountUsers: %w", err)
	}
	if q.countUsersByCreationDateStmt, err = db.PrepareContext(ctx, countUsersByCreationDate); err != nil {
		return nil, fmt.Errorf("error preparing query CountUsersByCreationDate: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.deleteUserByEmailStmt, err = db.PrepareContext(ctx, deleteUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserByEmail: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserCreationDateStmt, err = db.PrepareContext(ctx, getUserCreationDate); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserCreationDate: %w", err)
	}
	if q.getUserPasswordHashStmt, err = db.PrepareContext(ctx, getUserPasswordHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserPasswordHash: %w", err)
	}
	if q.listRecentUsersStmt, err = db.PrepareContext(ctx, listRecentUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecentUsers: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.listUsersByCreationDateStmt, err = db.PrepareContext(ctx, listUsersByCreationDate); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsersByCreationDate: %w", err)
	}
	if q.listUsersByIDsStmt, err = db.PrepareContext(ctx, listUsersByIDs); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsersByIDs: %w", err)
	}
	if q.updateUserEmailStmt, err = db.PrepareContext(ctx, updateUserEmail); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserEmail: %w", err)
	}
	if q.updateUserPasswordStmt, err = db.PrepareContext(ctx, updateUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPassword: %w", err)
	}
	if q.updateUserPasswordByEmailStmt, err = db.PrepareContext(ctx, updateUserPasswordByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPasswordByEmail: %w", err)
	}
	if q.updateUsernameStmt, err = db.PrepareContext(ctx, updateUsername); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUsername: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countUsersStmt != nil {
		if cerr := q.countUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUsersStmt: %w", cerr)
		}
	}
	if q.countUsersByCreationDateStmt != nil {
		if cerr := q.countUsersByCreationDateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUsersByCreationDateStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.deleteUserByEmailStmt != nil {
		if cerr := q.deleteUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserCreationDateStmt != nil {
		if cerr := q.getUserCreationDateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserCreationDateStmt: %w", cerr)
		}
	}
	if q.getUserPasswordHashStmt != nil {
		if cerr := q.getUserPasswordHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserPasswordHashStmt: %w", cerr)
		}
	}
	if q.listRecentUsersStmt != nil {
		if cerr := q.listRecentUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecentUsersStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.listUsersByCreationDateStmt != nil {
		if cerr := q.listUsersByCreationDateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersByCreationDateStmt: %w", cerr)
		}
	}
	if q.listUsersByIDsStmt != nil {
		if cerr := q.listUsersByIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersByIDsStmt: %w", cerr)
		}
	}
	if q.updateUserEmailStmt != nil {
		if cerr := q.updateUserEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserEmailStmt: %w", cerr)
		}
	}
	if q.updateUserPasswordStmt != nil {
		if cerr := q.updateUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPasswordStmt: %w", cerr)
		}
	}
	if q.updateUserPasswordByEmailStmt != nil {
		if cerr := q.updateUserPasswordByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPasswordByEmailStmt: %w", cerr)
		}
	}
	if q.updateUsernameStmt != nil {
		if cerr := q.updateUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUsernameStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                            DBTX
	tx                            *sql.Tx
	countUsersStmt                *sql.Stmt
	countUsersByCreationDateStmt  *sql.Stmt
	createUserStmt                *sql.Stmt
	deleteUserStmt                *sql.Stmt
	deleteUserByEmailStmt         *sql.Stmt
	getUserByEmailStmt            *sql.Stmt
	getUserByIDStmt               *sql.Stmt
	getUserCreationDateStmt       *sql.Stmt
	getUserPasswordHashStmt       *sql.Stmt
	listRecentUsersStmt           *sql.Stmt
	listUsersStmt                 *sql.Stmt
	listUsersByCreationDateStmt   *sql.Stmt
	listUsersByIDsStmt            *sql.Stmt
	updateUserEmailStmt           *sql.Stmt
	updateUserPasswordStmt        *sql.Stmt
	updateUserPasswordByEmailStmt *sql.Stmt
	updateUsernameStmt            *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                            tx,
		tx:                            tx,
		countUsersStmt:                q.countUsersStmt,
		countUsersByCreationDateStmt:  q.countUsersByCreationDateStmt,
		createUserStmt:                q.createUserStmt,
		deleteUserStmt:                q.deleteUserStmt,
		deleteUserByEmailStmt:         q.deleteUserByEmailStmt,
		getUserByEmailStmt:            q.getUserByEmailStmt,
		getUserByIDStmt:               q.getUserByIDStmt,
		getUserCreationDateStmt:       q.getUserCreationDateStmt,
		getUserPasswordHashStmt:       q.getUserPasswordHashStmt,
		listRecentUsersStmt:           q.listRecentUsersStmt,
		listUsersStmt:                 q.listUsersStmt,
		listUsersByCreationDateStmt:   q.listUsersByCreationDateStmt,
		listUsersByIDsStmt:            q.listUsersByIDsStmt,
		updateUserEmailStmt:           q.updateUserEmailStmt,
		updateUserPasswordStmt:        q.updateUserPasswordStmt,
		updateUserPasswordByEmailStmt: q.updateUserPasswordByEmailStmt,
		updateUsernameStmt:            q.updateUsernameStmt,
	}
}
