// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS count
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countUsersStmt, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByCreationDate = `-- name: CountUsersByCreationDate :one
SELECT COUNT(*) AS count
FROM users
WHERE created_at BETWEEN $1 AND $2
`

type CountUsersByCreationDateParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) CountUsersByCreationDate(ctx context.Context, arg CountUsersByCreationDateParams) (int64, error) {
	row := q.queryRow(ctx, q.countUsersByCreationDateStmt, countUsersByCreationDate, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, created_at)
VALUES ($1, $2, NOW())
RETURNING id, email, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	return err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :exec
DELETE FROM users
WHERE email = $1
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.exec(ctx, q.deleteUserByEmailStmt, deleteUserByEmail, email)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserCreationDate = `-- name: GetUserCreationDate :one
SELECT created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserCreationDate(ctx context.Context, id uuid.UUID) (time.Time, error) {
	row := q.queryRow(ctx, q.getUserCreationDateStmt, getUserCreationDate, id)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash
FROM users
WHERE id = $1
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.queryRow(ctx, q.getUserPasswordHashStmt, getUserPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const listRecentUsers = `-- name: ListRecentUsers :many
SELECT id, email, username, created_at
FROM users
WHERE created_at >= NOW() - INTERVAL '7 days'
ORDER BY created_at DESC
`

type ListRecentUsersRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListRecentUsers(ctx context.Context) ([]ListRecentUsersRow, error) {
	rows, err := q.query(ctx, q.listRecentUsersStmt, listRecentUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentUsersRow
	for rows.Next() {
		var i ListRecentUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, created_at
FROM users
ORDER BY created_at DESC
LIMIT $1
`

type ListUsersRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, limit int32) ([]ListUsersRow, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByCreationDate = `-- name: ListUsersByCreationDate :many
SELECT id, email, username, created_at
FROM users
WHERE created_at BETWEEN $1 AND $2
ORDER BY created_at DESC
`

type ListUsersByCreationDateParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type ListUsersByCreationDateRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListUsersByCreationDate(ctx context.Context, arg ListUsersByCreationDateParams) ([]ListUsersByCreationDateRow, error) {
	rows, err := q.query(ctx, q.listUsersByCreationDateStmt, listUsersByCreationDate, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByCreationDateRow
	for rows.Next() {
		var i ListUsersByCreationDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, email, username, created_at
FROM users
WHERE id = ANY($1)
ORDER BY created_at DESC
`

type ListUsersByIDsRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListUsersByIDs(ctx context.Context, id uuid.UUID) ([]ListUsersByIDsRow, error) {
	rows, err := q.query(ctx, q.listUsersByIDsStmt, listUsersByIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByIDsRow
	for rows.Next() {
		var i ListUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email = $2
WHERE id = $1
RETURNING id, email, created_at
`

type UpdateUserEmailParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

type UpdateUserEmailRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error) {
	row := q.queryRow(ctx, q.updateUserEmailStmt, updateUserEmail, arg.ID, arg.Email)
	var i UpdateUserEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2
WHERE id = $1
RETURNING id, email, created_at
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

type UpdateUserPasswordRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error) {
	row := q.queryRow(ctx, q.updateUserPasswordStmt, updateUserPassword, arg.ID, arg.PasswordHash)
	var i UpdateUserPasswordRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const updateUserPasswordByEmail = `-- name: UpdateUserPasswordByEmail :one
UPDATE users
SET password_hash = $2
WHERE email = $1
RETURNING id, email, created_at
`

type UpdateUserPasswordByEmailParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type UpdateUserPasswordByEmailRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) UpdateUserPasswordByEmail(ctx context.Context, arg UpdateUserPasswordByEmailParams) (UpdateUserPasswordByEmailRow, error) {
	row := q.queryRow(ctx, q.updateUserPasswordByEmailStmt, updateUserPasswordByEmail, arg.Email, arg.PasswordHash)
	var i UpdateUserPasswordByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const updateUsername = `-- name: UpdateUsername :one
UPDATE users
SET username = $2
WHERE id = $1
RETURNING id, email, username, created_at
`

type UpdateUsernameParams struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

type UpdateUsernameRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (UpdateUsernameRow, error) {
	row := q.queryRow(ctx, q.updateUsernameStmt, updateUsername, arg.ID, arg.Username)
	var i UpdateUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}
