// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sharing_sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PerformedBy pgtype.UUID        `json:"performed_by"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	EntityType  string             `json:"entity_type"`
	Action      string             `json:"action"`
	ChangedData []byte             `json:"changed_data"`
	PerformedAt pgtype.Timestamptz `json:"performed_at"`
}

type AuthSession struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type File struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ListingID      pgtype.UUID        `json:"listing_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	OriginalUrl    string             `json:"original_url"`
	WatermarkedUrl pgtype.Text        `json:"watermarked_url"`
	WatermarkType  pgtype.Text        `json:"watermark_type"`
	ThumbnailUrl   pgtype.Text        `json:"thumbnail_url"`
	FileSizeBytes  int64              `json:"file_size_bytes"`
	MimeType       string             `json:"mime_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Invoice struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	IssuedAt       pgtype.Timestamptz `json:"issued_at"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Listing struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	Visibility  string             `json:"visibility"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ListingPhoto struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ListingID   pgtype.UUID        `json:"listing_id"`
	FileID      pgtype.UUID        `json:"file_id"`
	Position    int32              `json:"position"`
	IsCover     bool               `json:"is_cover"`
	IsPublished bool               `json:"is_published"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Message   string             `json:"message"`
	Type      string             `json:"type"`
	Data      []byte             `json:"data"`
	IsRead    bool               `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	InvoiceID         pgtype.UUID        `json:"invoice_id"`
	SubscriptionID    pgtype.UUID        `json:"subscription_id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Currency          string             `json:"currency"`
	Status            string             `json:"status"`
	Method            string             `json:"method"`
	Provider          string             `json:"provider"`
	ProviderPaymentID string             `json:"provider_payment_id"`
	IdempotencyKey    string             `json:"idempotency_key"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
}

type Plan struct {
	ID           pgtype.UUID        `json:"id"`
	Type         string             `json:"type"`
	Price        pgtype.Numeric     `json:"price"`
	BillingCycle string             `json:"billing_cycle"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PlanLimit struct {
	PlanID           pgtype.UUID `json:"plan_id"`
	MaxStorageBytes  int64       `json:"max_storage_bytes"`
	MaxUploadBytes   int64       `json:"max_upload_bytes"`
	MaxListings      int32       `json:"max_listings"`
	MaxListingPhotos int32       `json:"max_listing_photos"`
}

type Refund struct {
	ID        pgtype.UUID      `json:"id"`
	PaymentID pgtype.UUID      `json:"payment_id"`
	TenantID  pgtype.UUID      `json:"tenant_id"`
	Amount    pgtype.Numeric   `json:"amount"`
	Reason    string           `json:"reason"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Role struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ShareLink struct {
	ID         pgtype.UUID        `json:"id"`
	ListingID  pgtype.UUID        `json:"listing_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Permission string             `json:"permission"`
	Token      string             `json:"token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	MaxViews   int32              `json:"max_views"`
	ViewCount  int32              `json:"view_count"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Subscription struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	PlanID    pgtype.UUID        `json:"plan_id"`
	Status    string             `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TenantSetting struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Theme            string             `json:"theme"`
	WatermarkEnabled bool               `json:"watermark_enabled"`
	WatermarkText    pgtype.Text        `json:"watermark_text"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TenantStorageUsage struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	UsedStorageBytes int64              `json:"used_storage_bytes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TenantUser struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UsageStat struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	UserID                pgtype.UUID        `json:"user_id"`
	TotalUploads          int64              `json:"total_uploads"`
	TotalStorageUsedBytes int64              `json:"total_storage_used_bytes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RoleID     pgtype.UUID        `json:"role_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}
