name: CI

on:
  push:
    branches: [main, feat]
  pull_request:
    branches: [main, feat]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/latest/download/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: Download deps
        run: make download-deps

      - name: Go mod tidy
        run: make tidy

      - name: Run migrations
        run: make migrate-up
        env:
          DB_URL: postgres://postgres:postgres@localhost:5432/testdb?sslmode=disable

      - name: Format check
        run: make fmt

      - name: Vet
        run: make vet

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
        run: make lint

      - name: Run tests
        run: make test

      - name: Build api
        run: make build-api
      
      - name: Build migrate
        run: make build-migrate