name: Orchestrator CI/CD

on:
  push :
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    name: Lint Codebase
    uses: ./.github/workflows/lint.yml
    with:
      sha: ${{ github.sha }}

  security:
    name: Run Security Checks
    needs: lint
    uses: ./.github/workflows/security.yml
    with:
      sha: ${{ github.sha }}

  ci:
    name: Run CI Workflow
    needs: security
    uses: ./.github/workflows/ci.yml
    with:
      sha: ${{ github.sha }}

  build:
    name: Run Docker Build Workflow
    needs: ci
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/docker-build.yml
    with:
      sha: ${{ github.sha }}

  migrate:
    name: Run Migrations Workflow
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/migrate.yml
    secrets: inherit
    with:
      sha: ${{ github.sha }}
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

  deploy-render-staging:
    name: Run Deploy Staging Workflow
    needs: migrate
    if: github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/deploy-staging.yml
    secrets: inherit
    with:
      sha: ${{ github.sha }}
      environment: staging

  deploy-render-production:
    name: Run Deploy Production Workflow
    needs: migrate
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-production.yml
    secrets: inherit
    with:
      sha: ${{ github.sha }}
      environment: production

  release:
    name: Run Release Workflow
    needs: deploy-render-production
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      sha: ${{ github.sha }}
      environment: production
